[project]
name = "indigenous-data-catalogue"
version = "0.1.0"
description = "Python scripts for managing data"
readme = "README.md"
authors = [
    { name = "jamiefeiss", email = "jamie.feiss@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "kgm>=2.1.2",
    "kurra>=3.0.6",
    "rdflib>=7.6.0",
]
