DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity/050308f6-67e6-52f6-82c9-56c20413cac6> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity/24e6bdb4-39f2-5b5c-b7d8-54d7cc8e7f9b> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity/2f133c6b-1d33-5f72-94a1-82b250dcf3ff> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity/34524ede-2abc-50f1-af30-8493753c928e> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity/3c2b10f8-eb83-5de4-b54d-28f7ed058109> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity/7c1def57-546e-5389-bde5-24d566944930> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity/92c9e33d-4ac3-5bc8-8bcb-e76171dd13c9> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity/9c0487c1-a143-57e0-874f-d3566a1b71e3> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity/b2d9f12b-163c-5975-a491-4989fae9ef78> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity/c8122728-6e9f-597c-b4d9-68b8858e66c7> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity/d689a611-e0e8-5972-bcbe-3cd0ebe94f0f> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity/dd9b004b-1c22-5b53-8381-bd93760ee922> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/reference/0cca8502-926a-5770-88a4-de3ae0d9c4e9> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/reference/180b6fcc-dcc6-5592-a390-5179366066fd> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/reference/97dd3be9-f4ca-586a-971a-594015bbfcc4> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/reference/ca68a358-3931-5011-adfd-0a695adc4812> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity-relationship/15763845-5c8b-5f08-8132-b4ee620da4ca> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity-relationship/19c443c8-9105-5c31-b602-fcc5242ad212> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity-relationship/21aeb88a-d1ea-5a87-9078-b5a2b0297767> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity-relationship/2b8edb62-2fd0-5f4a-b32b-f0a1e5053aa4> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity-relationship/755c7884-f6d1-54a3-8061-fb0913916af2> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity-relationship/ad363cfb-45e0-5e20-8f75-b0b06bb8080a> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity-relationship/d83fefdc-3a9c-5d1a-a136-856ab719c810> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity-relationship/e8c96d06-0760-5680-b6b8-242944e4fae7> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity-relationship/ea28496f-6d45-5ca5-809b-c39460067350> ;
DROP SILENT GRAPH <https://data.idnau.org/pid/resource/atns/entity-relationship/f54218ef-5ea0-521e-95ec-823b5ecf1736>
